name: CI model dockerhub
  
# Trigger
on:
  push:
    branches:
      - dev

  pull_request:
    branches:
    - dev

# Acciones 
jobs:
  build_docker_images:
    runs-on: ubuntu-latest

    steps:
      - name: Check the repo 
        uses: actions/checkout@v2
      
      - name: Login dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image 
        run: docker build -t jeralinfh/creditcardsfraud:v1 .
        
      - name: Docker push to Dockerhub
        run: docker push jeralinfh/creditcardsfraud:v1
